# Generated by Django 5.1.3 on 2024-12-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('employment_commencement_date', models.DateField()),
                ('annual_leave', models.IntegerField(default=0)),
                ('sick_leave', models.IntegerField(default=0)),
                ('toil', models.IntegerField(default=0)),
                ('bereavement_leave', models.IntegerField(default=0)),
                ('maternity_leave', models.IntegerField(default=0)),
                ('paternity_leave', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
