# Generated by Django 5.1.3 on 2024-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_commencement_date',
            field=models.DateField(default=0),
        ),
    ]
