# Generated by Django 5.1.3 on 2024-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='maternity_leave',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
