# Generated by Django 5.1.3 on 2024-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_employee_maternity_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bereavement_leave',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_commencement_date',
            field=models.DateField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='paternity_leave',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='toil',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
