# Generated by Django 5.1.3 on 2024-12-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_employee_annual_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
