# Generated by Django 5.1.3 on 2024-12-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_employee_employment_commencement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bereavement_leave',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maternity_leave',
            field=models.IntegerField(default=0),
        ),
    ]
