# Generated by Django 5.1.3 on 2024-12-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_employee_annual_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='toil',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
