# Generated by Django 5.1.3 on 2024-12-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_employee_annual_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bereavement_leave',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comments',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maternity_leave',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='paternity_leave',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
