# Generated by Django 5.1.3 on 2024-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_employee_bereavement_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comments',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
